appointments/urls.py
from django.urls import path
from . import views

app_name = "appointments"

urlpatterns = [
    path("", views.appointments_list, name="list"),
    path("<int:fk>/schedule", views.appointments_add, name="add"),
    path('<int:pk>/', views.appointments_details, name='details'),
    path('<int:pk>/edit/', views.appointments_edit, name='edit'),
    path('<int:pk>/delete/', views.appointments_delete, name='delete'),
]

authuser/urls.py
from django.urls import path, include
from .views import home


urlpatterns = [
    path("", include('allauth.urls')),
    path("home/", home, name="home"),
]

dental_delight/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index
from django.conf.urls.i18n import i18n_patterns

#TODO: Add multi language functionality
urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('users/', include('authuser.urls')),
    path("patients/", include('patients.urls')),
    path("dentists/", include('dentists.urls')),
    path("appointments/", include('appointments.urls')),
    path('', index, name='index'),
)

dentists/urls.py
from django.urls import path, include
from . import views

app_name = "dentists"

urlpatterns = [
    path("", views.dentists_list, name="list"),
    path("add/", views.dentist_add, name="add"),
    path('<int:pk>/', views.dentists_details, name='details'),
    path('<int:pk>/edit/', views.dentists_edit, name='edit'),
    path('<int:pk>/delete/', views.dentists_delete, name='delete'),
]

patients/urls.py
from django.urls import path, include
from . import views

app_name = "patients"

urlpatterns = [
    path("", views.patients_list, name="list"),
    path("add/", views.patients_add, name="add"),
    path('<int:pk>/', views.patients_details, name='details'),
    path('<int:pk>/edit/', views.patients_edit, name='edit'),
    path('<int:pk>/delete/', views.patients_delete, name='delete'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'core/index.html')

core/templates/core/base.html
<!DOCTYPE html>
<html>
    <head>
        {% include 'core/meta.html' %}
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body class="{% block body_class%}{% endblock %}">
            {% block content %}
            {% endblock %}
    </body>
</html>

core/templates/core/footer.html
<footer class="bottom-0 py-8 text-center bg-gray-200">
    <p class="text-xs text-gray-700">Copyright (c) 2024 Dental Delight</p>
</footer>

core/templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        {% include 'core/meta.html' %}
        <title>Dental Delight</title>
    </head>
    <body>
        <div class="container min-h-screen bg-[url({% static 'images/index_background.png'%})] relative bg-center bg-cover">
            <nav class="py-6 px-12 flex justify-between">
                <a href="{% url 'index' %}" class="text-3xl">Dental Delight <i class="fa-solid fa-tooth" style="color: rgb(125 211 252);"></i></a>
                <div class="space-x-2">
                    <a href="{% url 'account_login' %}" class="py-4 px-6 text-xl text-black hover:opacity-60">Log in</a>
                    <a href="{% url 'account_signup' %}" class="py-4 px-6 bg-sky-600 rounded-xl text-xl text-white transition duration-300 hover:bg-sky-700">Sign up</a>
                </div>
            </nav>
            <div class="px-28 mt-20">
                <div class="max-w-2xl">
                    <h1 class="text-7xl leading-normal">Productivity<br>just<span class="font-light"> one </span>click away</h1>
                    <p class="text-xl">Dental Delight offers a CRM solution to proffesional dentists to save their time and energy in managing their patients.</p>
                </div>
            </div>
            <img src="{% static 'images/index_dentist.png'%}" class="w-full xl:w-1/2 xl:absolute right-20 bottom-0">
            <footer class="absolute bottom-0 inset-x-0 py-4 text-center">
                <p class="text-xs">Copyright (c) 2024 Dental Delight</p>
            </footer>
        </div>
        
    </body>
</html>

core/templates/core/main_base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        {% include 'core/meta.html' %}
        <title>{% block title %}{% endblock %}</title>
    </head>

    <body class="bg-sky-50">
        <nav class="py-4 px-12 text-white flex justify-between bg-gray-700">
            <a href="{% url 'index' %}" class="text-2xl">Dental Delight <i class="fa-solid fa-tooth" style="color: rgb(125 211 252);"></i></a>
            <div class="space-x-2">
                <a href="{% url 'patients:list' %}" class="px-6 text-xl font-light text-gray-100 hover:opacity-60">Patients</a>
                <a href="{% url 'dentists:list' %}" class="px-6 text-xl font-light text-gray-100 hover:opacity-60">Dentists</a>
                <a href="{% url 'appointments:list' %}" class="px-6 text-xl font-light text-gray-100 hover:opacity-60">Appointments</a>
            </div>
            <div class="space-x-2">
                <a href="{% url 'account_logout' %}" class="py-3 px-6 text-xl text-white transition duration-300 hover:text-gray-400"><i class="fa-solid fa-right-from-bracket"></i></a>
            </div>
        </nav>
        <div class="p-5 h-screen bg-gray-100">
            <div id="messages" class="space-y-2 my-2">
                {% for message in messages %}
                    <div class="relative bg-emerald-50 border border-emerald-300 text-emerald-800 sm:text-sm rounded-lg block w-1/3 p-2.5">
                        {{ message }} <button onclick="return this.parentNode.remove();" class="absolute right-4 message_button"><i class="fa-solid fa-x fa-2xs"></i></button>
                    </div>
                {% endfor %}
            </div>
            {% block content %}
            {% endblock %}
        </div>
        <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
        <script src="https://cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
        <script src="https://cdn.datatables.net/1.13.4/js/dataTables.bootstrap5.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.4.1/js/dataTables.responsive.min.js"></script>
        <script src="https://cdn.datatables.net/responsive/2.4.1/js/responsive.bootstrap5.min.js"></script>
        <script src="{% static 'js/table.js' %}"></script> 
    </body>
</html>

core/templates/core/meta.html
{% load static %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">  
<script src="https://cdn.tailwindcss.com"></script>
<link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
<link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
<link rel="stylesheet"
        href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.3.0-alpha3/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.4/css/dataTables.bootstrap5.min.css">
<link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.4.1/css/responsive.bootstrap5.min.css">