authuser/urls.py
from django.urls import path, include
from .views import home


urlpatterns = [
    path("", include('allauth.urls')),
    path("home/", home, name="home"),
]

dental_delight/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index
from django.conf.urls.i18n import i18n_patterns

#TODO: Add multi language functionality
urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('users/', include('authuser.urls')),
    path("patients/", include('patients.urls')),
    path("dentists/", include('dentists.urls')),
    path("appointments/", include('appointments.urls')),
    path('', index, name='index'),
)

dentists/urls.py
from django.urls import path, include
from . import views

app_name = "dentists"

urlpatterns = [
    path("", views.dentists_list, name="list"),
    path("add/", views.dentist_add, name="add"),
    path('<int:pk>/', views.dentists_details, name='details'),
    path('<int:pk>/edit/', views.dentists_edit, name='edit'),
    path('<int:pk>/delete/', views.dentists_delete, name='delete'),
]

dentists/models.py
from django.db import models
from core.validators import only_int
from authuser.models import User

class Dentist(models.Model):
    first_name = models.CharField(max_length=255, blank= False, null=False)
    last_name = models.CharField(max_length=255, blank= False, null=False)
    email = models.EmailField(unique=True, blank= False, null=False)
    phone_number = models.CharField(max_length=255, blank= False, null=False)
    citizen_number = models.CharField(max_length=255, validators=[only_int], unique=True, blank=False, null=False)
    ENDODONTIST  = 'endodontist'
    ORTHODONTIST = 'orthodontist'
    PERIODONTIST = 'periodontist'
    PROSTHODONTIST = 'prosthodontist'
    MAXILLOFACIAL_SURGEON = 'maxillofacial_surgeon'
    MAXILLOFACIAL_RADIOLOGIST = 'maxillofacial_radiologist'
    ANESTHESIOLOGISTS = 'anesthesiologists'
    MAXILLOFACIAL_PATHOLOGIST = 'maxillofacial_pathologist'
    PEDIATRIC_DENTIST = 'pediatric_dentist'
    OROFACIAL_PAIN = 'orofacial_pain'
    ORAL_MEDICINE = 'oral_medicine'
    DENTAL_PUBLIC_HEALTH = 'dental_public_health'
    GENERAL_DENTISTRY = 'general_dentistry'
    COSMETIC_DENTISTRY = 'cosmetic_dentistry'
    RESTORATIVE_DENTISTRY = 'restorative_dentistry'
    GERIATRIC_DENTISTRY = 'geriatric_dentistry'
    DENTAL_HYGIENIST = 'dental_hygienist'
    DENTAL_ASSISTANT = 'dental_assistant'
    
    CHOICES_SPECIALITY = (
        (ENDODONTIST, 'Endodontist'),
        (ORTHODONTIST, 'Orthodontist'),
        (PERIODONTIST, 'Periodontist'),
        (PROSTHODONTIST, 'Prosthodontist'),
        (MAXILLOFACIAL_SURGEON, 'Maxillofacial Surgeon'),
        (MAXILLOFACIAL_RADIOLOGIST, 'Maxillofacial Radiologist'),
        (ANESTHESIOLOGISTS, 'Anesthesiologists'),
        (MAXILLOFACIAL_PATHOLOGIST, 'Maxillofacial Pathologist'),
        (PEDIATRIC_DENTIST, 'Pediatric Dentist'),
        (OROFACIAL_PAIN, 'Orofacial Pain'),
        (ORAL_MEDICINE, 'Oral Medicine'),
        (DENTAL_PUBLIC_HEALTH, 'Dental Public Health'),
        (GENERAL_DENTISTRY, 'General Dentistry'),
        (COSMETIC_DENTISTRY, 'Cosmetic Dentistry'),
        (RESTORATIVE_DENTISTRY, 'Restorative Dentistry'),
        (GERIATRIC_DENTISTRY, 'Geriatric dentistry'),
        (DENTAL_HYGIENIST, 'Dental Hygienist'),
        (DENTAL_ASSISTANT, 'Dental Assistant'),
    )
    speciality = models.CharField(max_length=30, choices=CHOICES_SPECIALITY, default=GENERAL_DENTISTRY)
    created_by = models.ForeignKey(User, related_name='dentists', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["first_name"]
    
    def get_short_name(self):
        return self.first_name
    
    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def __str__(self):
        return self.get_full_name()

dentists/forms.py
from django import forms
from .models import Dentist
from django.utils.translation import gettext_lazy as _

class AddDentistForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=30, 
        label=_('First Name'),
        widget=forms.TextInput(
            attrs={"type": "text", "placeholder": _("Leo") }
        )
    )
    last_name = forms.CharField(
        max_length=30, 
        label=_('Last Name'),
        widget=forms.TextInput(
            attrs={"type": "text", "placeholder": _("Messi") }
        )
    )
    email = forms.EmailField(
        label=_("Email"),
        required=True,
        widget=forms.TextInput(
            attrs={"type": "email", "placeholder": _("someaddress@domain.com")}
        ),
    )
    phone_number = forms.CharField(
        max_length=30, 
        label=_('Phone Number'),
        widget=forms.TextInput(
            attrs={"type": "text", "placeholder": _("(555) 555-1234") }
        )
    )
    citizen_number = forms.CharField(
        max_length=30, 
        label=_('Citizen Number'),
        widget=forms.TextInput(
            attrs={"type": "text", "placeholder": _("123456789") }
        )
    )

    class Meta:
        model = Dentist
        fields = ["first_name", "last_name", "email", "phone_number", "citizen_number", "speciality" ]

dentists/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import AddDentistForm
from .models import Dentist
from django.contrib import messages

@login_required
def dentists_list(request):
    dentists = Dentist.objects.filter(created_by=request.user)
    return render(request, "dentists/dentists_list.html", {"dentists": dentists})

@login_required
def dentists_details(request, pk):
    dentist = get_object_or_404(request.user.dentists, pk=pk)

    return render(request, "dentists/dentists_details.html", {"dentist": dentist})


@login_required
def dentist_add(request):
    context = {"title": "Create New Dentist"}
    if request.method == "POST":
        form = AddDentistForm(request.POST)

        if form.is_valid():
            dentist = form.save(commit=False)
            dentist.created_by = request.user
            dentist.save()

            return redirect("dentists:list")
        else:
            context["form"] = form
            return render(request, "dentists/dentists_form.html", context)

    else:
        form = AddDentistForm()
        context["form"] = form
        return render(request, "dentists/dentists_form.html", context)

@login_required
def dentists_edit(request, pk):
    context = {"title": "Edit Dentist"}
    dentist = get_object_or_404(request.user.dentists, pk=pk)
    if request.method == "POST":
        form = AddDentistForm(request.POST, request.FILES, instance=dentist)

        if form.is_valid():
            form.save()

            messages.success(request, 'The Dentist was edited successfully')
            
            return redirect("dentists:list")
        else:
            context["form"] = form
            return render(request, "dentists/dentists_form.html", context)

    else:
        form = AddDentistForm(instance=dentist)
        context["form"] = form
        return render(request, "dentists/dentists_form.html", context)

@login_required
def dentists_delete(request, pk):
    dentist = get_object_or_404(request.user.dentists, pk=pk)
    if request.method == "POST":
        dentist.delete()

        messages.success(request, 'The Dentist was deleted succesfully! ')
        return redirect("dentists:list")

    else:
        return render(request, "dentists/dentists_delete.html", {"dentist": dentist})

    

dentists/templates/dentists/dentists_delete.html
{% extends 'core/main_base.html' %}
{% load widget_tweaks %}
{% block title %}Confirmation Delete{% endblock %}
{% block content %}
<div class="grid justify-items-end mb-6">
    <a href="{% url 'dentists:list' %}" class="py-2 px-4 text-white bg-sky-600 hover:bg-sky-700 font-medium rounded-lg text-center">Return to Dentists</a>
</div>

<div class="flex items-center justify-center mx-auto ">
    <div class="w-full bg-white rounded-lg shadow border md:mt-0 sm:max-w-md xl:p-0" >
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <form method="post" action="">
                {% csrf_token %}
                <div class="space-y-6 mb-5">
                    <h1 class="text-2xl text-gray-900">
                        Are you sure you want to delete {{ dentist.get_full_name }}?
                    </h1>
                </div>
                <button type="submit" class="px-5 py-2 text-white bg-red-600 hover:bg-red-700 font-medium text-sm rounded-lg text-center">Confirm Delete</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

dentists/templates/dentists/dentists_details.html
{% extends 'core/main_base.html' %}
{% block title %}{{ dentist.get_full_name }}'s Details {% endblock %}
{% block content %}
<div class="bg-white overflow-hidden shadow rounded-lg border w-2/3">
    <div class="px-8 py-5 ">
        <h3 class="text-3xl font-medium text-gray-900">
            {{ dentist.get_full_name }}
        </h3>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 ">
        <dl class="divide-y divide-gray-200">
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    First Name
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ dentist.first_name }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Last Name
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ dentist.last_name }} 
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Email 
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">                 
                    {{ dentist.email }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Phone Number
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ dentist.phone_number }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Citizen Number 
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ dentist.citizen_number }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Created At
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ dentist.created_at }}
                </dd>
            </div>
            <div class="mb-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Modified At 
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ dentist.modified_at }}
                </dd>
            </div>      
            <a href= "{% url 'dentists:edit' dentist.id %}" class="ml-5 px-5 py-2 text-white bg-sky-600 hover:bg-sky-700 font-medium text-sm rounded-lg text-center">Edit</a>
            <a href= "{% url 'dentists:delete' dentist.id %}" class="ml-5 px-5 py-2 text-white bg-red-600 hover:bg-red-700 font-medium text-sm rounded-lg text-center">Delete</a>
        </dl>
    </div>
</div>
{% endblock %}

dentists/templates/dentists/dentists_form.html
{% extends 'core/main_base.html' %}
{% load widget_tweaks %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="grid justify-items-end mb-6">
    <a href="{% url 'dentists:list' %}" class="py-2 px-4 text-white bg-sky-600 hover:bg-sky-700 font-medium rounded-lg text-center">Return to Dentists</a>
</div>

<div class="flex items-center justify-center mx-auto ">
    <div class="w-full bg-white rounded-lg shadow border md:mt-0 sm:max-w-md xl:p-0" >
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <form method="post" action="">
                {% csrf_token %}
                <div class="space-y-6 mb-5">
                    <h1 class="text-2xl text-gray-900">
                        {{ title }}
                    </h1>
                    <div class="flex justify-items-start space-x-3">
                        {% for field in form %}
                            {% if "name" in field.name %}
                            <div>
                                <label class="block mb-2 text-sm font-light text-gray-900">{{field.label}}</label>
                                {{ field|append_attr:"class:bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5" }}
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="space-y-2">
                        {% for field in form %}
                            {% if "name" not in field.name and field.name != 'profile_picture' %}
                                <label class="block mb-2 text-sm font-light text-gray-900">{{field.label}}</label>           
                                {{ field|append_attr:"class:bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5" }}
                            {% elif field.name == 'profile_picture' %}
                            {{ field.path }}
                            <div class="shrink-0">
                                <img class="h-16 w-16 object-cover rounded-full" src="{{ field.value }}" alt="Current profile photo" />
                              </div>
                                <label class="block mb-2 text-sm font-light text-gray-900">{{field.label}}</label> 
                                <div class="flex items-center space-x-6">
                                    {{ field|append_attr:"class:bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5 file:mr-4 file:py-2 file:px-4 file:rounded-full file:border-0 file:text-sm file:bg-gray-100 file:text-gray-500 hover:file:bg-gray-100" }}                            
                                </div>          
                                
                            {% endif %}
                        {% endfor %}
                        
                    </div>
                    
                    {% if form.errors or form.non_field_errors %} 
                        {% include 'core/messages/errors.html' %}       
                    {% endif %}
                    {% if messages %}
                        {% include 'core/messages/messages.html' %}
                    {% endif %}
                </div>
                <button type="submit" class="px-5 py-2 text-white bg-sky-600 hover:bg-sky-700 font-medium text-sm rounded-lg text-center">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

dentists/templates/dentists/dentists_list.html
{% extends 'core/main_base.html' %}
{% block title %}{{ user.get_short_name }}'s Dentists{% endblock %}
{% block content %}
<div class="flex justify-between mb-6 items-center">
    <h1 class="text-2xl text-gray-900">
      Dentists
    </h1>
    <a href="{% url 'dentists:add' %}" class="py-2 px-4 text-white bg-sky-600 hover:bg-sky-700 font-medium rounded-lg text-center">Add Dentist</a>
</div>


<table id="table" class="table table-striped table-bordered" style="width:100%">
  <thead class="text-xs text-gray-700 uppercase bg-gray-50">
    <tr>
      <th scope="col" class="px-6 py-3">
          Dentist Name
      </th>
      <th scope="col" class="px-6 py-3">
          Email
      </th>
      <th scope="col" class="px-6 py-3">
          Phone Number
      </th>
      <th scope="col" class="px-6 py-3">
          Citizen Number
      </th>
      <th scope="col" class="px-6 py-3">
          Speciality
      </th>
      <th scope="col" class="px-6 py-3">
          Created At
      </th>
      <th scope="col" class="px-6 py-3">
          Modified At
      </th>
      <th scope="col" class="px-6 py-3">
          Action
      </th>
    </tr>
  </thead>
  <tbody>
    {% for dentist in dentists %}
    <tr class="bg-white">
        <td class="px-6 py-4">
            {{ dentist.get_full_name }}
        </td>
        <td class="px-6 py-4">
          {{ dentist.email }}
        </td>
        <td class="px-6 py-4">
          {{ dentist.phone_number }}
        </td>
        <td class="px-6 py-4">
          {{ dentist.citizen_number }}
        </td>
        <td class="px-6 py-4">
          {{ dentist.get_speciality_display }}
        </td>
        <td class="px-6 py-4">
          {{ dentist.created_at }}
        </td>
        <td class="px-6 py-4">
          {{ dentist.modified_at }}
        </td>
        <td class="px-6 py-4 text-center space-x-2">
            <a href="{% url 'dentists:edit' dentist.id %}" class="font-medium text-blue-600 hover:underline">Edit</a>
            <a href="{% url 'dentists:details' dentist.id %}" class="font-medium text-blue-600 hover:underline">View</a>
            <a href="{% url 'dentists:delete' dentist.id %}" class="font-medium text-red-600 hover:underline">Delete</a>
        </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}