appointments/urls.py
from django.urls import path
from . import views

app_name = "appointments"

urlpatterns = [
    path("", views.appointments_list, name="list"),
    path("<int:fk>/schedule", views.appointments_add, name="add"),
    path('<int:pk>/', views.appointments_details, name='details'),
    path('<int:pk>/edit/', views.appointments_edit, name='edit'),
    path('<int:pk>/delete/', views.appointments_delete, name='delete'),
]

authuser/urls.py
from django.urls import path, include
from .views import home


urlpatterns = [
    path("", include('allauth.urls')),
    path("home/", home, name="home"),
]

dental_delight/urls.py
from django.contrib import admin
from django.urls import path, include
from core.views import index
from django.conf.urls.i18n import i18n_patterns

#TODO: Add multi language functionality
urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('users/', include('authuser.urls')),
    path("patients/", include('patients.urls')),
    path("dentists/", include('dentists.urls')),
    path("appointments/", include('appointments.urls')),
    path('', index, name='index'),
)

patients/urls.py
from django.urls import path, include
from . import views

app_name = "patients"

urlpatterns = [
    path("", views.patients_list, name="list"),
    path("add/", views.patients_add, name="add"),
    path('<int:pk>/', views.patients_details, name='details'),
    path('<int:pk>/edit/', views.patients_edit, name='edit'),
    path('<int:pk>/delete/', views.patients_delete, name='delete'),
]

patients/models.py
from django.db import models
from core.validators import only_int
from authuser.models import User

class Patient(models.Model):
    first_name = models.CharField(max_length=255, blank= False, null=False)
    last_name = models.CharField(max_length=255, blank= False, null=False)
    email = models.EmailField(unique=True, blank= False, null=False)
    phone_number = models.CharField(max_length=255, blank= False, null=False)
    citizen_number = models.CharField(max_length=255, validators=[only_int], unique=True, blank=False, null=False)
    created_by = models.ForeignKey(User, related_name='patients', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["first_name"]
    
    def get_short_name(self):
        return self.first_name
    
    def get_full_name(self):
        return self.first_name + " " + self.last_name

    def __str__(self):
        return self.get_full_name()

patients/forms.py
from django import forms
from .models import Patient
from django.utils.translation import gettext_lazy as _

class AddPatientForm(forms.ModelForm):
    first_name = forms.CharField(
        max_length=30, 
        label=_('First Name'),
        widget=forms.TextInput(
            attrs={"type": "text", "placeholder": _("Leo") }
        )
    )
    last_name = forms.CharField(
        max_length=30, 
        label=_('Last Name'),
        widget=forms.TextInput(
            attrs={"type": "text", "placeholder": _("Messi") }
        )
    )
    email = forms.EmailField(
        label=_("Email"),
        required=True,
        widget=forms.TextInput(
            attrs={"type": "email", "placeholder": _("someaddress@domain.com")}
        ),
    )
    phone_number = forms.CharField(
        max_length=30, 
        label=_('Phone Number'),
        widget=forms.TextInput(
            attrs={"type": "text", "placeholder": _("(555) 555-1234") }
        )
    )
    citizen_number = forms.CharField(
        max_length=30, 
        label=_('Citizen Number'),
        widget=forms.TextInput(
            attrs={"type": "text", "placeholder": _("123456789") }
        )
    )

    class Meta:
        model = Patient
        fields = ["first_name", "last_name", "email", "phone_number", "citizen_number"]

patients/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import AddPatientForm
from .models import Patient
from django.contrib import messages

@login_required
def patients_list(request):
    patients = Patient.objects.filter(created_by=request.user)
    return render(request, "patients/patients_list.html", {"patients": patients})

@login_required
def patients_details(request, pk):
    patient = get_object_or_404(request.user.patients, pk=pk)

    return render(request, "patients/patients_details.html", {"patient": patient})


@login_required
def patients_add(request):
    context = {"title": "Create New Patient"}
    if request.method == "POST":
        form = AddPatientForm(request.POST)

        if form.is_valid():
            patient = form.save(commit=False)
            patient.created_by = request.user
            patient.save()

            return redirect("patients:list")
        else:
            context["form"] = form
            return render(request, "patients/patients_form.html", context)

    else:
        form = AddPatientForm()
        context["form"] = form
        return render(request, "patients/patients_form.html", context)

@login_required
def patients_edit(request, pk):
    context = {"title": "Edit Patient"}
    patient = get_object_or_404(request.user.patients, pk=pk)
    if request.method == "POST":
        form = AddPatientForm(request.POST, instance=patient)

        if form.is_valid():
            form.save()

            messages.success(request, 'The Patient was edited successfully')
            
            return redirect("patients:list")
        else:
            context["form"] = form
            return render(request, "patients/patients_form.html", context)

    else:
        form = AddPatientForm(instance=patient)
        context["form"] = form
        return render(request, "patients/patients_form.html", context)

@login_required
def patients_delete(request, pk):
    patient = get_object_or_404(request.user.patients, pk=pk)
    if request.method == "POST":
        patient.delete()

        messages.success(request, 'The Patient was deleted succesfully! ')
        return redirect("patients:list")

    else:
        return render(request, "patients/patients_delete.html", {"patient": patient})

    

patients/templates/patients/patients_delete.html
{% extends 'core/main_base.html' %}
{% load widget_tweaks %}
{% block title %}Confirmation Delete{% endblock %}
{% block content %}
<div class="grid justify-items-end mb-6">
    <a href="{% url 'patients:list' %}" class="py-2 px-4 text-white bg-sky-600 hover:bg-sky-700 font-medium rounded-lg text-center">Return to Patients</a>
</div>

<div class="flex items-center justify-center mx-auto ">
    <div class="w-full bg-white rounded-lg shadow border md:mt-0 sm:max-w-md xl:p-0" >
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <form method="post" action="">
                {% csrf_token %}
                <div class="space-y-6 mb-5">
                    <h1 class="text-2xl text-gray-900">
                        Are you sure you want to delete {{ patient.get_full_name }}?
                    </h1>
                </div>
                <button type="submit" class="px-5 py-2 text-white bg-red-600 hover:bg-red-700 font-medium text-sm rounded-lg text-center">Confirm Delete</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

patients/templates/patients/patients_details.html
{% extends 'core/main_base.html' %}
{% block title %}{{ patient.get_full_name }}'s Details {% endblock %}
{% block content %}
<div class="bg-white overflow-hidden shadow rounded-lg border w-2/3">
    <div class="px-8 py-5 ">
        <h3 class="text-3xl font-medium text-gray-900">
            {{ patient.get_full_name }}
        </h3>
    </div>
    <div class="border-t border-gray-200 px-4 py-5 ">
        <dl class="divide-y divide-gray-200">
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    First Name
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ patient.first_name }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Last Name
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ patient.last_name }} 
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Email 
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">                 
                    {{ patient.email }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Phone Number
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ patient.phone_number }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Citizen Number 
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ patient.citizen_number }}
                </dd>
            </div>
            <div class="py-3 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Created At
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ patient.created_at }}
                </dd>
            </div>
            <div class="mb-4 sm:py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
                <dt class="text-sm font-medium text-gray-500">
                    Modified At 
                </dt>
                <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
                    {{ patient.modified_at }}
                </dd>
            </div>      
            <a href= "{% url 'patients:edit' patient.id %}" class="ml-5 px-5 py-2 text-white bg-sky-600 hover:bg-sky-700 font-medium text-sm rounded-lg text-center">Edit</a>
            <a href= "{% url 'appointments:add' patient.id %}" class="ml-5 px-5 py-2 text-white bg-sky-600 hover:bg-sky-700 font-medium text-sm rounded-lg text-center">Schedule Appointment</a>
            <a href= "{% url 'patients:delete' patient.id %}" class="ml-5 px-5 py-2 text-white bg-red-600 hover:bg-red-700 font-medium text-sm rounded-lg text-center">Delete</a>
        </dl>
    </div>
</div>
{% endblock %}

patients/templates/patients/patients_form.html
{% extends 'core/main_base.html' %}
{% load widget_tweaks %}
{% block title %}{{ title }}{% endblock %}
{% block content %}
<div class="grid justify-items-end mb-6">
    <a href="{% url 'patients:list' %}" class="py-2 px-4 text-white bg-sky-600 hover:bg-sky-700 font-medium rounded-lg text-center">Return to Patients</a>
</div>

<div class="flex items-center justify-center mx-auto ">
    <div class="w-full bg-white rounded-lg shadow border md:mt-0 sm:max-w-md xl:p-0" >
        <div class="p-6 space-y-4 md:space-y-6 sm:p-8">
            <form method="post" action="">
                {% csrf_token %}
                <div class="space-y-6 mb-5">
                    <h1 class="text-2xl text-gray-900">
                        {{ title }}
                    </h1>
                    <div class="flex justify-items-start space-x-3">
                        {% for field in form %}
                            {% if "name" in field.name %}
                            <div>
                                <label class="block mb-2 text-sm font-light text-gray-900">{{field.label}}</label>
                                {{ field|append_attr:"class:bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5" }}
                            </div>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="space-y-2">
                        {% for field in form %}
                            {% if "name" not in field.name %}
                                <label class="block mb-2 text-sm font-light text-gray-900">{{field.label}}</label>
                                {{ field|append_attr:"class:bg-gray-50 border border-gray-300 text-gray-900 sm:text-sm rounded-lg block w-full p-2.5" }}
                            {% endif %}
                        {% endfor %}
                    </div>
                    {% if form.errors or form.non_field_errors %} 
                        {% include 'core/messages/errors.html' %}       
                    {% endif %}
                    {% if messages %}
                        {% include 'core/messages/messages.html' %}
                    {% endif %}
                </div>
                <button type="submit" class="px-5 py-2 text-white bg-sky-600 hover:bg-sky-700 font-medium text-sm rounded-lg text-center">Save</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

patients/templates/patients/patients_list.html
{% extends 'core/main_base.html' %}
{% load static %}
{% block title %}{{ user.get_short_name }}'s Patients{% endblock %}
{% block content %}
<div class="flex justify-between mb-6 items-center">
    <h1 class="text-2xl text-gray-900">
        Patients
    </h1>
    <a href="{% url 'patients:add' %}" class="py-2 px-4 text-white bg-sky-600 hover:bg-sky-700 font-medium rounded-lg text-center">Add Patient</a>
</div>

<table id="table" class="table table-striped table-bordered" style="width:100%">
  <thead class="text-xs text-gray-700 uppercase bg-gray-50">
    <tr>
      <th >
          Patient Name
      </th>
      <th >
          Email
      </th>
      <th >
          Phone Number
      </th>
      <th >
          Citizen Number
      </th>
      <th>
          Created At
      </th>
      <th>
          Modified At
      </th>
      <th >
          Action
      </th>
    </tr>
  </thead>
  <tbody>
    {% for patient in patients %}
    <tr class="bg-white">
        <td class="px-6 py-4">
            {{ patient.get_full_name }}
        </td>
        <td class="px-6 py-4">
          {{ patient.email }}
        </td>
        <td class="px-6 py-4">
          {{ patient.phone_number }}
        </td>
        <td class="px-6 py-4">
          {{ patient.citizen_number }}
        </td>
        <td class="px-6 py-4">
          {{ patient.created_at }}
        </td>
        <td class="px-6 py-4">
          {{ patient.modified_at }}
        </td>
        <td class="px-6 py-4 text-center space-x-2">
            <a href="{% url 'patients:edit' patient.id %}" class="font-medium text-blue-600 hover:underline">Edit</a>
            <a href="{% url 'patients:details' patient.id %}" class="font-medium text-blue-600 hover:underline">View</a>
            <a href="{% url 'appointments:add' patient.id %}" class="font-medium text-blue-600 hover:underline">Schedule</a>
            <a href="{% url 'patients:delete' patient.id %}" class="font-medium text-red-600 hover:underline">Delete</a>
        </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

{% endblock %}